v=input('enter a plural noun:')
a=input('enter an adjective:')
sn=input('enter a noun:')
ad=input('enter an adjective:')
print(f'Being stuck at home during a/an {sn} -storm is the worst! My {ad} brother Charlie has been banging on his {v} all day. It is driving me totally {a}, and I am not the only one!')